### ISSUE TITLE
Errors when running the code

### ISSUE THREAD

**Issue by RicciWoo** [madrugado/Attention-Based-Aspect-Extraction#1]
When running python3 train.py with the preprocessed dataset, I have this error message:
    AttributeError: 'Word2Vec' object has no attribute 'vocabulary'

When running python3 preprocess.py, encounters an error message:
    [Errno 2] No such file or directory: '../preprocessed_data/app_reviews/appstore.json'

**Comment by madrugado** [comment]
Dear RicciWoo, 

The first error is related to gensim package version. Please make sure that you have met the requirements in your environment: `gensim<=3.1`

The second error is related to the missing data, you could run the `preprocess.py` with other domain data, as described in readme. But thank you for pointing out, I will change the default domain value.
