### ISSUE TITLE
'Keyword argument not understood:', 'input_dtype'

### ISSUE THREAD

**Issue by shahad-mahmud** [madrugado/Attention-Based-Aspect-Extraction#24]
While training, the following error is raised. 

> Traceback (most recent call last):
>   File "train.py", line 101, in <module>
>     model = create_model(args, overall_maxlen, vocab)
>   File "/media/shahad/Work_and_resources/Projects/Python_projects/machine_learning/thesis_related/Attention-Based-Aspect-Extraction/code/model.py", line 55, in create_model
>     r_s = WeightedAspectEmb(args.aspect_size, args.emb_dim, name='aspect_emb',
>   File "/media/shahad/Work_and_resources/Projects/Python_projects/machine_learning/thesis_related/Attention-Based-Aspect-Extraction/code/my_layers.py", line 132, in __init__
>     super(WeightedAspectEmb, self).__init__(**kwargs)
>   File "/home/shahad/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
>     result = method(self, *args, **kwargs)
>   File "/home/shahad/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 340, in __init__
>     generic_utils.validate_kwargs(kwargs, allowed_kwargs)
>   File "/home/shahad/.local/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 808, in validate_kwargs
>     raise TypeError(error_message, kwarg)
> TypeError: ('Keyword argument not understood:', 'input_dtype')

**Comment by kuraga** [comment]
@shahad-mahmud which dependency versions do you have?

**Comment by shahad-mahmud** [comment]
I have the following dependencies. 
gensim==3.8.3
keras==2.4.3
numpy==1.19.5
tensorflow==2.4.0
theano==1.0.5

**Comment by kuraga** [comment]
@shahad-mahmud ,

Tensorflow should be  1.4:

https://github.com/madrugado/Attention-Based-Aspect-Extraction/blob/d0c457d14a9541596d889eb773cccf01be98c0ca/requirements.txt#L3

**Comment by trannhatquy** [comment]
actually I use tensorflow~=1.4 but then I still have the error above, what should I do now ? @kuraga

**Comment by eegdecoder** [comment]
Hi I have the same problem as mentioned above

**Comment by sputnikav** [comment]
Having the same issues with `keras==2.4.3` and `tensorflow==2.4.0`, could anyone give a dependency list that works?

**Comment by nzlul03** [comment]
I have the same problem as mentioned above

**Comment by schwinge** [comment]
same here with tf v2.8.2, keras: 2.8.0
